[package]
name = "order_processor"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
either = "1.15.0"
itertools = "0.14.0"
rayon = "1.10.0"
regex = "1.11.1"
strsim = "0.11.1"
xlsxwriter = "0.6.1"
