[package]
name = "order_processor"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.26.0"
chrono = "0.4.41"
colored = "3.0.0"
either = "1.15.0"
itertools = "0.14.0"
once_cell = "1.21.3"
rayon = "1.10.0"
regex = "1.11.1"
strsim = "0.11.1"
xlsxwriter = "0.6.1"
